language: node_js
node_js:
  - 12
install:
  - pip install --user awscli
script:
  - npm install
  - npm build
  - npm export
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  local-dir: ./out
  skip_cleanup: true
  region: eu-west-2
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
